# Site settings
title: Elena Torró
email: elenatorro@gmail.com
description: "Welcome to my personal webpage :)"
baseurl: ""
url: ""
twitter_username: elenarcolepsia
github_username:  elenatorro

# Build settings
markdown: kramdown
permalink: pretty
